<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\DB;

abstract class TestCase extends BaseTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete('delete from table_users_addcarts_products');
        DB::delete('delete from carts');
        DB::delete('delete from purchases');
        DB::delete('delete from transactions');
        DB::delete('delete from user_payments');
        DB::delete('delete from payment_methods');
        DB::delete("delete from reviews");
        DB::delete("delete from products");
        DB::delete('delete from user_details');
        DB::delete('delete from users');
        DB::delete('delete from categories');
    }
}
