<?php

namespace Tests\Feature;

use App\services\ProductService;
use Database\Seeders\CategorySeeder;
use Database\Seeders\ProductSeeder;
use Database\Seeders\ReviewSeeder;
use Database\Seeders\UserDetailSeeder;
use Database\Seeders\UserSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ProductServiceTest extends TestCase
{
    private ProductService $productService;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->productService = $this->app->make(ProductService::class);
    }

    public function testProductServiceNotNull()
    {
        self::assertNotNull($this->productService);
    }

    public function testGetDataIndex()
    {
        $this->seed([UserSeeder::class, UserDetailSeeder::class, CategorySeeder::class, ProductSeeder::class, ReviewSeeder::class]);

        $data = $this->productService->getDataIndex(8);
        self::assertNotNull($data);
        self::assertNotNull([$data['newProducts']]);
        self::assertNotNull([$data['reviews']]);
    }
}
