<?php

namespace Tests\Feature;

use App\Models\User;
use App\Repositories\UserRepository;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserRepositoryTest extends TestCase
{
    protected UserRepository $userRepository;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userRepository = $this->app->make(UserRepository::class);
    }

    public function testUserRepoNotNull()
    {
        self::assertNotNull($this->userRepository);
    }

    public function testCreateAndLogin()
    {
        $user = $this->userRepository->create([
            'name' => 'hasanhusain',
            'username' => 'hasanhusain',
            'email' => 'hasanhusain@gmail.com',
            'password' => 'hasanhusain'
        ]);

        self::assertEquals('hasanhusain', $user->name);

        $user = $this->userRepository->attemptLogin([
            'username' => 'hasanhusain@gmail.com',
            'password' => 'hasanhusain'
        ]);

        self::assertTrue($user);
    }
}
