<?php

namespace Tests\Feature;

use App\Services\UserService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserServiceTest extends TestCase
{
    private UserService $userService;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->userService = $this->app->make(UserService::class);
    }

    public function testUserServiceNotNull()
    {
        self::assertNotNull($this->userService);
    }

    public function testRegisterAndLogin()
    {
        $user = $this->userService->register([
            'name' => 'hasanhusain',
            'username' => 'hasanhusain',
            'email' => 'hasanhusain@gmail.com',
            'password' => 'hasanhusain'
        ]);

        self::assertEquals('hasanhusain', $user->name);

        self::assertTrue($this->userService->login([
            'username' => $user->email,
            'password' => 'hasanhusain',
        ]));
    }
}
